import Foundation
import SafeWorldCore

/// Serves the Safari Content Blocker rule list. The host app rebuilds this
/// list from the user's settings (`SafeWorldCore.BlockerListBuilder`) and
/// writes it to the shared App Group container whenever settings change,
/// then asks Safari to reload it. Before the app has run once, this falls
/// back to the default list bundled with the extension (all default-enabled
/// categories, generated by `npm run build:ios`).
final class ContentBlockerRequestHandler: NSObject, NSExtensionRequestHandling {
    func beginRequest(with context: NSExtensionContext) {
        let url = Self.blockerListURL()
        let attachment = url.flatMap { NSItemProvider(contentsOf: $0) }
            ?? NSItemProvider(item: Data("[]".utf8) as NSSecureCoding, typeIdentifier: "public.json")

        let item = NSExtensionItem()
        item.attachments = [attachment]
        context.completeRequest(returningItems: [item], completionHandler: nil)
    }

    private static func blockerListURL() -> URL? {
        let fm = FileManager.default
        if let shared = AppGroup.blockerListURL(), fm.fileExists(atPath: shared.path) {
            return shared
        }
        return Bundle.main.url(forResource: "blockerList", withExtension: "json")
    }
}
