package com.safeworld.core

/**
 * Parses a third-party blocklist the *user* subscribed to, on-device.
 *
 * Hand-port of `packages/core/src/feed.ts`. Unlike the bundled lists, which are
 * generated by a build script on a machine we control, these files are fetched
 * at runtime from someone else's server — so this parser is the only thing
 * standing between an upstream syntax change and a subscription that reports
 * "enabled" while blocking nothing extra.
 *
 * That is why [FeedParserTest] pins the same vectors as `feed.test.ts`, the same
 * arrangement `DomainHasherTest` and `ScrambleTests` use: divergence here is
 * silent, and silence is the failure mode that matters.
 */
object FeedParser {

    /**
     * Line formats the upstream feeds actually use, verified against the live
     * files rather than assumed:
     *
     * - [HOSTS]       `0.0.0.0 example.com`   StevenBlack, blocklistproject
     * - [DOMAINS]     `example.com`           plain one-per-line
     * - [DOMAINSWILD] `*.example.com`         oisd
     * - [ADBLOCK]     `||example.com^`        hagezi
     */
    enum class Format(val id: String) {
        HOSTS("hosts"),
        DOMAINS("domains"),
        DOMAINSWILD("domainswild"),
        ADBLOCK("adblock");

        companion object {
            /** Falls back to [DOMAINS], the least structured format. */
            fun from(id: String): Format = entries.firstOrNull { it.id == id } ?: DOMAINS
        }
    }

    /**
     * Hostnames a hosts file legitimately maps that are not blocking targets.
     * Without this, parsing a hosts-style feed picks up "localhost" and the app
     * cheerfully sinkholes the loopback name.
     */
    private val PLACEHOLDER_HOSTS = setOf(
        "localhost",
        "localhost.localdomain",
        "local",
        "broadcasthost",
        "ip6-localhost",
        "ip6-loopback",
        "ip6-localnet",
        "ip6-mcastprefix",
        "ip6-allnodes",
        "ip6-allrouters",
        "ip6-allhosts",
        "0.0.0.0",
    )

    /**
     * Top-level domains it is safe — and intended — to block whole.
     *
     * A bare domain with no dot is normally rejected, because storing `com`
     * would make [Matcher.hostMatchesDomain] match every host under it and take
     * out most of the web. But the live feeds deliberately publish exactly that
     * for the adult TLDs: `||www.xxx^`, `*.porn`, `*.sex`, `*.adult`. Those were
     * the only lines any feed lost, and for an adult-content blocker each is
     * worth more than any single domain in the file.
     *
     * So the guard keeps its teeth and gains a whitelist. Every entry is an
     * ICANN-sponsored TLD whose entire purpose is the content we block. Adding
     * to this list blocks an entire TLD — do it only for one with no legitimate
     * use for our users. **Must match `BLOCKABLE_TLDS` in feed.ts.**
     */
    private val BLOCKABLE_TLDS = setOf(
        "xxx", "porn", "sex", "adult", "sexy", "cam", "tube",
        "casino", "bet", "poker", "bingo",
    )

    /** `||example.com^`, optionally with a trailing `^`, and nothing else. */
    private val ADBLOCK_PLAIN = Regex("^\\|\\|([a-z0-9.-]+)\\^?$", RegexOption.IGNORE_CASE)

    private val IPV4 = Regex("^\\d{1,3}(\\.\\d{1,3}){3}$")

    private val WHITESPACE = Regex("\\s+")

    /** True for a line that carries no rule at all: blank, comment, or preamble. */
    private fun isIgnorable(trimmed: String): Boolean =
        trimmed.isEmpty() ||
            trimmed.startsWith("#") ||
            trimmed.startsWith("!") ||
            trimmed.startsWith("[")

    /**
     * One line to one domain, or null when the line carries nothing we can
     * block.
     *
     * Returns null rather than throwing: these files are hundreds of thousands
     * of lines maintained by other people, and one unparseable line must cost
     * that line rather than the whole subscription.
     */
    fun parseLine(line: String, format: Format): String? {
        val trimmed = line.trim()
        if (isIgnorable(trimmed)) return null

        // An adblock exception (`@@||example.com^`) means "do not block". We
        // cannot express that as an addition to a blocklist, so the line is
        // skipped. Ignoring it can only leave something unblocked that upstream
        // also left unblocked — never the reverse.
        if (trimmed.startsWith("@@")) return null

        val candidate: String? = when (format) {
            Format.HOSTS -> {
                // "0.0.0.0 example.com" / "127.0.0.1 example.com # comment"
                val parts = trimmed.split(WHITESPACE)
                if (parts.size < 2) null else parts[1]
            }
            Format.DOMAINS -> trimmed.split(WHITESPACE).firstOrNull()
            Format.DOMAINSWILD -> {
                val first = trimmed.split(WHITESPACE).firstOrNull() ?: ""
                // `*.example.com` means the domain and its subdomains — exactly
                // what hostMatchesDomain already does, so the prefix is dropped
                // rather than carried into the stored domain.
                if (first.startsWith("*.")) first.substring(2) else first
            }
            Format.ADBLOCK ->
                // Anything with a path, wildcard, or `$modifier` is a URL-level
                // rule a DNS layer cannot express. Skipped rather than mangled
                // into a domain block broader than the author intended.
                ADBLOCK_PLAIN.find(trimmed)?.groupValues?.get(1)
        }

        if (candidate == null) return null

        val host = Matcher.normalizeHost(candidate)
        if (host.isEmpty()) return null
        if (host in PLACEHOLDER_HOSTS) return null
        if (IPV4.matches(host)) return null
        if (!host.contains('.') && host !in BLOCKABLE_TLDS) return null
        if (host.contains('*')) return null

        return host
    }

    /**
     * @param domains de-duplicated, in first-seen order.
     * @param skipped lines that carried no usable domain, excluding comments and
     *   blanks — so "0 domains, 400,000 skipped" says the format is wrong while
     *   "0 and 0" says the body was empty. Collapsing those two would make a
     *   misconfigured subscription look like a failed download.
     */
    data class Parsed(val domains: List<String>, val skipped: Int)

    fun parse(text: String, format: Format): Parsed {
        val seen = LinkedHashSet<String>()
        var skipped = 0

        // lineSequence avoids materialising a 450,000-element array of lines on
        // top of the 9 MB string itself, which matters on a phone.
        for (line in text.lineSequence()) {
            val domain = parseLine(line, format)
            if (domain == null) {
                if (!isIgnorable(line.trim())) skipped++
                continue
            }
            seen.add(domain)
        }

        return Parsed(seen.toList(), skipped)
    }
}
